apiVersion: apps/v1
kind: Deployment
metadata:
  name: moncv-deployment
  labels:
    app: moncv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moncv
  template:
    metadata:
      labels:
        app: moncv
    spec:
      containers:
      - name: moncv
        image: manardarghouthi/moncv:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

