server:
  log_level: info

metrics:
  global:
    scrape_interval: 15s
  configs:
  - name: integrations
    remote_write:
      - url: "https://<GRAFANA_REMOTE_WRITE_ENDPOINT>"
        basic_auth:
          username: "admin"
          password: "admin"
    scrape_configs:
      - job_name: node_exporter
        static_configs:
          - targets: ['localhost:9100']
      - job_name: cadvisor
        static_configs:
          - targets: ['localhost:8080']

