- name: Install prerequisites
  apt:
    name: ['ca-certificates','curl','gnupg','lsb-release']
    update_cache: yes
    state: present

- name: Add Docker official GPG key
  ansible.builtin.command: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker apt repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\n"

- name: Install docker packages
  apt:
    name: ['docker-ce','docker-ce-cli','containerd.io']
    state: latest
    update_cache: yes

- name: Ensure docker service running
  systemd:
    name: docker
    state: started
    enabled: true

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

